spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.237.137:3306/order?characterEncoding=utf-8&useSSL=false
    username: root
    password: 361116
env: prd
girl:
  name: CYS
  age: 20
