eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/
      #如果客户端没启动 服务不可调用 心跳机制 自我保护机制 开发环境可以关掉 生产环境要打开
    register-with-eureka: false
  server:
    enable-self-preservation: false
spring:
  application:
    name: eureka
#server:
#  port: 8761j